[package]
name = "typedb-examples"
version = "0.1.0"
edition = "2021"

[lib]
name = "typedb_examples"
path = "src/lib.rs"

[dependencies]
typeql = "3.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"